using Microsoft.AspNetCore.Mvc;

namespace AutoGenerateData
{
    [Route("api/[controller]")]
    [ApiController]
    public class MemberApiController : ControllerBase
    {
        private readonly ISQLBulkCopyService _sQLBulkCopyService;

        public MemberApiController(ISQLBulkCopyService sQLBulkCopyService) 
        {
            _sQLBulkCopyService = sQLBulkCopyService;
        }

        [HttpPost]
        public void InsertData()
        {
            _sQLBulkCopyService.InsertData(_sQLBulkCopyService.TransferTypeToDataTable(typeof(Member)), $"dbo.{nameof(Member)}", typeof(Member));
        }
    }
}
