using Microsoft.AspNetCore.Mvc;

namespace AutoGenerateData
{
    [Route("api/[controller]")]
    [ApiController]
    public class MemberAdditionalInfoApiController : ControllerBase
    {
        private readonly ISQLBulkCopyService _sQLBulkCopyService;

        public MemberAdditionalInfoApiController(ISQLBulkCopyService sQLBulkCopyService)
        {
            _sQLBulkCopyService = sQLBulkCopyService;
        }

        [HttpPost]
        public void InsertData()
        {
            _sQLBulkCopyService.InsertData(_sQLBulkCopyService.TransferTypeToDataTable(typeof(MemberAdditionalInfo)), $"dbo.{nameof(MemberAdditionalInfo)}", typeof(MemberAdditionalInfo));
        }
    }
}
