using Microsoft.AspNetCore.Mvc;

namespace AutoGenerateData
{
    [Route("api/[controller]")]
    [ApiController]
    public class SystemManagementApiController : ControllerBase
    {
        private readonly ISQLBulkCopyService _sQLBulkCopyService;

        public SystemManagementApiController(ISQLBulkCopyService sQLBulkCopyService)
        {
            _sQLBulkCopyService = sQLBulkCopyService;
        }

        [HttpPost]
        public void InsertData()
        {
            _sQLBulkCopyService.InsertData(_sQLBulkCopyService.TransferTypeToDataTable(typeof(SystemManagement)), $"dbo.{nameof(SystemManagement)}", typeof(SystemManagement));
        }
    }
}
