using System.Data;

namespace AutoGenerateData
{
    public interface ISQLBulkCopyService
    {
        public DataTable TransferTypeToDataTable(Type objectType);
        public void InsertData(DataTable dt, string tableName, Type type);
    }
}
