using Microsoft.Data.SqlClient;
using System.Data;
using System.Reflection;

namespace AutoGenerateData
{
    public class SQLBulkCopyService : ISQLBulkCopyService
    {
        private readonly IConfiguration Configuration;
        private readonly string _conn;

        private int _insertCount = 100;
        private delegate T SetValue<T>();

        public SQLBulkCopyService(IConfiguration configuration)
        {
            Configuration = configuration;
            _conn = Configuration["ConnectionString"] ?? @"Data Source=./;Initial Catalog = DBPractise;Integrated Security = True;TrustServerCertificate=True;";
        }


        /// <summary>
        /// Generate Interger Type Data
        /// </summary>
        /// <returns></returns>
        private int AssignIntValue()
        {
            return new Random().Next(100);
        }

        /// <summary>
        /// Generate Guid Type Data
        /// </summary>
        /// <returns></returns>
        private Guid AssignGuidValue()
        {
            return Guid.NewGuid();
        }

        /// <summary>
        /// Generate String Type Data
        /// </summary>
        /// <returns></returns>
        private string AssignStringValue()
        {
            string[] strArr = new string[] { "Joseph", "Michael", "John", "Marry" };
            return strArr[new Random().Next(strArr.Length)];
        }

        private T SetTypeValue<T>(SetValue<T> value)
        {
            return value.Invoke();
        }


        /// <summary>
        /// Invoke the procedure to auto generate data 
        /// </summary>
        /// <param name="objectType"></param>
        /// <returns></returns>
        public DataTable TransferTypeToDataTable(Type objectType)
        {
            var dt = new DataTable();
            IEnumerable<PropertyInfo> props = objectType.GetProperties();

            foreach (var item in props)
            {
                dt.Columns.Add(item.Name, item.PropertyType);
            }

            for (int i = 0; i < _insertCount; i++)
            {
                var row = dt.NewRow();
                foreach (var item in props)
                {
                    Type type = item.PropertyType;
                    row[item.Name] = type.Name switch
                    {
                        nameof(Int32) => SetTypeValue<int>(AssignIntValue),
                        nameof(String) => SetTypeValue<string>(AssignStringValue),
                        nameof(Guid) => SetTypeValue<Guid>(AssignGuidValue),
                        _=> default
                    };
                }
                dt.Rows.Add(row);
            }
            return dt;
        }

        public void InsertData(DataTable dt, string tableName, Type type)
        {
            IEnumerable<PropertyInfo> props = type.GetProperties();
            using (var sql = new SqlConnection(_conn))
            {
                sql.Open();
                using (var sqlBulkCopy = new SqlBulkCopy(sql))
                {
                    sqlBulkCopy.DestinationTableName = tableName;
                    foreach (var item in props)
                    {
                        sqlBulkCopy.ColumnMappings.Add(item.Name, item.Name);
                    }
                    sqlBulkCopy.WriteToServer(dt);
                }
            }
        }
    }
 }
